// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddParticipant(ctx context.Context, arg AddParticipantParams) (SessionParticipant, error)
	CheckEmailOrUsernameExists(ctx context.Context, arg CheckEmailOrUsernameExistsParams) (CheckEmailOrUsernameExistsRow, error)
	CheckJoinCodeExists(ctx context.Context, joinCode string) (bool, error)
	CountQuestionsByQuiz(ctx context.Context, quizID int64) (int64, error)
	CountQuizListByOwner(ctx context.Context, arg CountQuizListByOwnerParams) (int64, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateQuiz(ctx context.Context, arg CreateQuizParams) (Quiz, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (QuizSession, error)
	DeleteQuestion(ctx context.Context, id int64) error
	DeleteQuiz(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	EndSession(ctx context.Context, id int64) error
	FindEmailSignUp(ctx context.Context, email string) (FindEmailSignUpRow, error)
	FindUsernameSignUp(ctx context.Context, username string) (FindUsernameSignUpRow, error)
	FindValidateName(ctx context.Context, arg FindValidateNameParams) (FindValidateNameRow, error)
	GetCurrentQuestion(ctx context.Context, id int64) (Question, error)
	GetMaxQuestionIndexByQuiz(ctx context.Context, quizID int64) (int32, error)
	GetPublicQuizzes(ctx context.Context, arg GetPublicQuizzesParams) ([]GetPublicQuizzesRow, error)
	GetQuestionByID(ctx context.Context, id int64) (Question, error)
	GetQuestionByQuizAndIndex(ctx context.Context, arg GetQuestionByQuizAndIndexParams) (Question, error)
	GetQuestionListByQuiz(ctx context.Context, quizID int64) ([]Question, error)
	GetQuizListByOwner(ctx context.Context, arg GetQuizListByOwnerParams) ([]Quiz, error)
	GetQuizWithOwner(ctx context.Context, id int64) (GetQuizWithOwnerRow, error)
	GetSessionByID(ctx context.Context, id int64) (GetSessionByIDRow, error)
	GetSessionByJoinCode(ctx context.Context, joinCode string) (GetSessionByJoinCodeRow, error)
	GetSessionLeaderboard(ctx context.Context, sessionID int64) ([]GetSessionLeaderboardRow, error)
	GetSessionParticipants(ctx context.Context, sessionID int64) ([]SessionParticipant, error)
	GetUserByEmailIncludePassword(ctx context.Context, email string) (User, error)
	GetUserDetail(ctx context.Context, id int64) (GetUserDetailRow, error)
	IncrementQuizPlayCount(ctx context.Context, id int64) error
	IncrementQuizViewCount(ctx context.Context, id int64) error
	RegisterAccount(ctx context.Context, arg RegisterAccountParams) (RegisterAccountRow, error)
	StartSession(ctx context.Context, id int64) error
	UpdateParticipantScore(ctx context.Context, arg UpdateParticipantScoreParams) error
	UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error)
	UpdateQuestionIndex(ctx context.Context, arg UpdateQuestionIndexParams) error
	UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (Quiz, error)
	UpdateQuizTotalQuestions(ctx context.Context, arg UpdateQuizTotalQuestionsParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (QuizSession, error)
	UpdateSessionQuestion(ctx context.Context, arg UpdateSessionQuestionParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserLastLogin(ctx context.Context, id int64) (UpdateUserLastLoginRow, error)
}

var _ Querier = (*Queries)(nil)
